export const validIcons = {
    html5: {
        id: 0,
        name: "HTML5",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg",
        iconType: "full-stack",
    },
    css3: {
        id: 1,
        name: "CSS3",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg",
        iconType: "full-stack",
    },
    javascript: {
        id: 2,
        name: "JavaScript",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg",
        iconType: "full-stack",
    },
    typescript: {
        id: 3,
        name: "TypeScript",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg",
        iconType: "full-stack",
    },
    react: {
        id: 4,
        name: "React",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg",
        iconType: "full-stack",
    },
    tailwind: {
        id: 5,
        name: "Tailwind",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg",
        iconType: "full-stack",
    },
    nodejs: {
        id: 6,
        name: "Node.js",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg",
        iconType: "full-stack",
    },
    express: {
        id: 7,
        name: "Express",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg",
        iconType: "full-stack",
    },
    figma: {
        id: 8,
        name: "Figma",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg",
        iconType: "full-stack",
    },
    postgresql: {
        id: 9,
        name: "PostgreSQL",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original.svg",
        iconType: "full-stack",
    },
    mysql: {
        id: 10,
        name: "MySQL",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original.svg",
        iconType: "full-stack",
    },
    docker: {
        id: 11,
        name: "Docker",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-original.svg",
        iconType: "full-stack",
    },
    git: {
        id: 12,
        name: "Git",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg",
        iconType: "full-stack",
    },
    axios: {
        id: 13,
        name: "Axios",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/axios/axios-plain.svg",
        iconType: "full-stack",
    },
    bootstrap: {
        id: 14,
        name: "Bootstrap",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bootstrap/bootstrap-original.svg",
        iconType: "full-stack",
    },
    postman: {
        id: 15,
        name: "Postman",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postman/postman-original.svg",
        iconType: "full-stack",
    },
    rust: {
        id: 16,
        name: "Rust",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/rust/rust-original.svg",
        iconType: "other",
    },
    cplusplus: {
        id: 17,
        name: "C++",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cplusplus/cplusplus-original.svg",
        iconType: "other",
    },
    python: {
        id: 18,
        name: "Python",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg",
        iconType: "other",
    },
    playwright: {
        id: 19,
        name: "Playwright",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/playwright/playwright-original.svg",
        iconType: "other",
    },
    linux: {
        id: 20,
        name: "Linux",
        imgUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/linux/linux-original.svg",
        iconType: "other",
    },
} as const;

export type IconKey = keyof typeof validIcons;
